# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de Position',
                'verbose_name_plural': 'Historiques de Positions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MissionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('pickup', 'Point de ramassage'), ('delivery', 'Point de livraison'), ('current', 'Position actuelle')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.TextField()),
                ('city', models.CharField(default='Ouagadougou', max_length=100)),
                ('country', models.CharField(default='BF', max_length=3)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position de Mission',
                'verbose_name_plural': 'Positions de Missions',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Ouagadougou', max_length=100)),
                ('country', models.CharField(default='BF', max_length=3)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Position Utilisateur',
                'verbose_name_plural': 'Positions Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geofence_type', models.CharField(choices=[('pickup_zone', 'Zone de ramassage'), ('delivery_zone', 'Zone de livraison'), ('restricted_zone', 'Zone restreinte'), ('service_zone', 'Zone de service')], max_length=20)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone Géographique',
                'verbose_name_plural': 'Zones Géographiques',
                'indexes': [models.Index(fields=['geofence_type', 'is_active'], name='location_ge_geofenc_e32cfa_idx'), models.Index(fields=['center_latitude', 'center_longitude'], name='location_ge_center__07b9d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('enter_zone', 'Entrée dans une zone'), ('exit_zone', "Sortie d'une zone"), ('near_destination', 'Proche de la destination'), ('off_route', 'Déviation de route'), ('speed_limit', 'Limite de vitesse')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.geofence')),
            ],
            options={
                'verbose_name': 'Alerte de Géolocalisation',
                'verbose_name_plural': 'Alertes de Géolocalisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
