# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionlocation',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='locationalert',
            index=models.Index(fields=['user', 'is_read'], name='location_lo_user_id_4c6c12_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='location_lo_alert_t_8e0efa_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['user', 'timestamp'], name='location_lo_user_id_0cb54e_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['timestamp'], name='location_lo_timesta_c089cf_idx'),
        ),
        migrations.AddIndex(
            model_name='missionlocation',
            index=models.Index(fields=['mission', 'location_type'], name='location_mi_mission_83b79f_idx'),
        ),
        migrations.AddIndex(
            model_name='missionlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='location_mi_latitud_a410ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionlocation',
            unique_together={('mission', 'location_type')},
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='location_us_latitud_3f3527_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'is_active'], name='location_us_user_id_0e2bcc_idx'),
        ),
    ]
