# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryrating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='categoryrating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.ratingcategory'),
        ),
        migrations.AddField(
            model_name='ratingresponse',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='ratings.rating'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'rated_user', 'mission')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryrating',
            unique_together={('rating', 'category')},
        ),
    ]
