# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('priority', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('express', 'Express')], default='normale', max_length=20)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_instructions', models.TextField(blank=True)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('colis_petit', 'Petit colis'), ('colis_moyen', 'Colis moyen'), ('colis_volumineux', 'Colis volumineux'), ('nourriture', 'Nourriture'), ('medicament', 'Médicament'), ('autre', 'Autre')], default='colis_petit', max_length=20)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('package_dimensions', models.CharField(blank=True, max_length=100)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo_pickup', 'Photo de ramassage'), ('photo_delivery', 'Photo de livraison'), ('signature', 'Signature'), ('autre', 'Autre')], max_length=50)),
                ('file', models.FileField(upload_to='mission_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document de Mission',
                'verbose_name_plural': 'Documents de Missions',
            },
        ),
        migrations.CreateModel(
            name='MissionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suivi de Mission',
                'verbose_name_plural': 'Suivis de Missions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
