# Generated by Django 5.2.4 on 2025-12-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
