# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('user_management', 'Gestion utilisateurs'), ('mission_management', 'Gestion missions'), ('system_config', 'Configuration système'), ('security', 'Sécurité'), ('content_management', 'Gestion contenu'), ('financial', 'Financier'), ('reporting', 'Rapports'), ('maintenance', 'Maintenance')], db_index=True, max_length=30)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_object_type', models.CharField(blank=True, max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('admin_action', 'Action Admin'), ('system_event', 'Événement Système'), ('security_event', 'Événement Sécurité'), ('api_call', 'Appel API'), ('error', 'Erreur'), ('warning', 'Avertissement')], db_index=True, max_length=20)),
                ('action_description', models.CharField(default='Action système', max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('export_type', models.CharField(choices=[('users', 'Utilisateurs'), ('missions', 'Missions'), ('financial', 'Données financières'), ('analytics', 'Analytics'), ('audit_logs', "Logs d'audit"), ('system_data', 'Données système')], db_index=True, max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('records_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('contains_sensitive_data', models.BooleanField(default=False)),
                ('access_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('failed_login', 'Tentative de connexion échouée'), ('suspicious_activity', 'Activité suspecte'), ('permission_denied', 'Accès refusé'), ('rate_limit_exceeded', 'Limite de taux dépassée'), ('invalid_token', 'Token invalide'), ('sql_injection_attempt', "Tentative d'injection SQL"), ('xss_attempt', 'Tentative XSS'), ('csrf_failure', 'Échec CSRF'), ('brute_force', 'Attaque par force brute'), ('account_locked', 'Compte verrouillé'), ('password_changed', 'Mot de passe modifié'), ('admin_privilege_escalation', 'Escalade de privilèges admin')], db_index=True, max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('is_investigated', models.BooleanField(default=False)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('active_users', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('api_requests_per_minute', models.IntegerField(default=0)),
                ('database_connections', models.IntegerField(default=0)),
                ('missions_created_today', models.IntegerField(default=0)),
                ('missions_completed_today', models.IntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_users_today', models.IntegerField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('system_status', models.CharField(choices=[('healthy', 'Sain'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('down', 'Hors service')], default='healthy', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
