# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['timestamp'], name='audit_syste_timesta_1f765d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['system_status', 'timestamp'], name='audit_syste_system__5f24c2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['admin_user', 'timestamp'], name='audit_admin_admin_u_b39658_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['category', 'timestamp'], name='audit_admin_categor_4dc0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['is_critical', 'timestamp'], name='audit_admin_is_crit_39c101_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'action_type'], name='audit_audit_timesta_478407_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_audit_severit_4d72db_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['user', 'timestamp'], name='audit_datae_user_id_b92d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['export_type', 'timestamp'], name='audit_datae_export__2117f2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['timestamp', 'risk_level'], name='audit_secur_timesta_b968cb_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['source_ip', 'timestamp'], name='audit_secur_source__9a372d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_secur_event_t_cc3542_idx'),
        ),
    ]
