# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_adresse', models.CharField(choices=[('domicile', 'Domicile'), ('travail', 'Travail'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('adresse_complete', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adresse Favorite',
                'verbose_name_plural': 'Adresses Favorites',
                'ordering': ['-is_default', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quantite', models.CharField(default='1', max_length=50)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courses_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article de Courses',
                'verbose_name_plural': 'Articles de Courses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_addresses', models.JSONField(default=dict, help_text='Adresses favorites du client')),
                ('default_payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire'), ('especes', 'Espèces')], default='orange_money', max_length=50)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='EstimationPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.TextField()),
                ('adresse_arrivee', models.TextField()),
                ('type_colis', models.CharField(max_length=50)),
                ('priorite', models.CharField(max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_estime', models.PositiveIntegerField(help_text='Délai en minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_converted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estimation de Prix',
                'verbose_name_plural': 'Estimations de Prix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liste de Courses',
                'verbose_name_plural': 'Listes de Courses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire')], max_length=50)),
                ('nom_affiche', models.CharField(max_length=100)),
                ('numero_masque', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moyen de Paiement',
                'verbose_name_plural': 'Moyens de Paiement',
                'ordering': ['-is_default', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire'), ('especes', 'Espèces')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
