# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_dashboard', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adressefavorite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationprix',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listecourses',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecourses',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='client_dashboard.listecourses'),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='missions.mission'),
        ),
    ]
