# Generated by Django 5.2.4 on 2025-12-29 13:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(help_text="Ordre de l'étape (1, 2, 3...)")),
                ('type_etape', models.CharField(choices=[('depart', 'Point de départ'), ('achat', "Lieu d'achat"), ('depot', 'Dépôt intermédiaire'), ('livraison', 'Livraison finale')], max_length=20)),
                ('adresse', models.TextField(help_text="Adresse complète de l'étape")),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions spécifiques pour cette étape')),
                ('action_requise', models.TextField(help_text='Action à effectuer à cette étape')),
                ('montant_requis', models.DecimalField(blank=True, decimal_places=2, help_text="Montant d'argent requis (ex: pour récupérer ou acheter)", max_digits=10, null=True)),
                ('est_validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Étape de Mission',
                'verbose_name_plural': 'Étapes de Mission',
                'ordering': ['numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCourseMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'article", max_length=200)),
                ('quantite', models.CharField(default='1', help_text="Quantité (ex: '2 kg', '3 pièces')", max_length=50)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Prix estimé (facultatif)', max_digits=8, null=True)),
                ('prix_max_accepte', models.DecimalField(blank=True, decimal_places=2, help_text='Prix maximum accepté', max_digits=8, null=True)),
                ('prix_reel', models.DecimalField(blank=True, decimal_places=2, help_text='Prix réel payé (rempli par le livreur)', max_digits=8, null=True)),
                ('substitution_autorisee', models.BooleanField(default=False, help_text='Substitution autorisée si article indisponible')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire libre')),
                ('est_achete', models.BooleanField(default=False)),
                ('photo_produit', models.ImageField(blank=True, null=True, upload_to='courses_photos/')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='client_dashboard.etapemission')),
            ],
            options={
                'verbose_name': 'Article de Course',
                'verbose_name_plural': 'Articles de Course',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MissionCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la mission de courses', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description générale de la mission')),
                ('status', models.CharField(choices=[('creee', 'Créée'), ('payee', 'Payée'), ('publiee', 'Publiée'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='creee', max_length=20)),
                ('etape_actuelle', models.PositiveIntegerField(default=1, help_text="Numéro de l'étape en cours")),
                ('delai_type', models.CharField(choices=[('heure_limite', 'Heure limite'), ('duree_max', 'Durée maximum')], default='duree_max', max_length=20)),
                ('heure_limite', models.DateTimeField(blank=True, help_text="Heure limite si delai_type = 'heure_limite'", null=True)),
                ('duree_max_minutes', models.PositiveIntegerField(blank=True, help_text="Durée max en minutes si delai_type = 'duree_max'", null=True)),
                ('delai_debut', models.DateTimeField(blank=True, help_text='Moment où le délai commence (après acceptation)', null=True)),
                ('distance_totale_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance totale calculée', max_digits=8, null=True)),
                ('tarif_km', models.DecimalField(decimal_places=2, default=500.0, help_text='Tarif par km en FCFA', max_digits=8)),
                ('frais_service', models.DecimalField(decimal_places=2, default=1000.0, help_text='Frais de service fixes', max_digits=8)),
                ('surcharge_urgence', models.DecimalField(decimal_places=2, default=0.0, help_text='Surcharge si délai court', max_digits=8)),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='Prix total calculé', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_courses', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant total des courses à acheter', max_digits=10)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('candidats', models.ManyToManyField(blank=True, related_name='missions_courses_postulees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_courses', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_courses_acceptees', to=settings.AUTH_USER_MODEL)),
                ('transaction_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_courses', to='client_dashboard.transaction')),
            ],
            options={
                'verbose_name': 'Mission de Courses',
                'verbose_name_plural': 'Missions de Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='etapemission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='client_dashboard.missioncourses'),
        ),
        migrations.CreateModel(
            name='ValidationEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_preuve', models.CharField(choices=[('photo', 'Photo'), ('recu', 'Reçu'), ('signature', 'Signature'), ('confirmation', 'Confirmation')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='validations_etapes/')),
                ('commentaire', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='client_dashboard.etapemission')),
            ],
            options={
                'verbose_name': "Validation d'Étape",
                'verbose_name_plural': "Validations d'Étapes",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='etapemission',
            unique_together={('mission', 'numero_ordre')},
        ),
    ]
