# Generated by Django 5.2.5 on 2025-09-06 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('cash', 'Espèces')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('moov', 'Moov'), ('orange', 'Orange'), ('telecel', 'Telecel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_received', 'Paiement reçu'), ('payment_failed', 'Paiement échoué'), ('subscription_expiring', 'Abonnement expirant'), ('payment_reminder', 'Rappel de paiement')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification de Paiement',
                'verbose_name_plural': 'Notifications de Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20, verbose_name='Type de plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix (FCFA)')),
                ('duration', models.IntegerField(default=30, help_text='Durée en jours (ex: 30, 90, 365)', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.TextField(help_text='Liste des avantages séparés par des virgules', verbose_name='Fonctionnalités')),
                ('max_missions_per_month', models.PositiveIntegerField(default=10, verbose_name='Missions max/mois')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Support prioritaire')),
                ('advanced_analytics', models.BooleanField(default=False, verbose_name='Analytics avancées')),
                ('multi_user_management', models.BooleanField(default=False, verbose_name='Gestion multi-utilisateurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'Abonnement",
                'verbose_name_plural': "Plans d'Abonnement",
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('canceled', 'Annulé'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé')),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('stripe', 'Stripe')], max_length=50, verbose_name='Méthode de paiement')),
            ],
            options={
                'verbose_name': 'Abonnement Utilisateur',
                'verbose_name_plural': 'Abonnements Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
